---
registrations: 
    /fields
authorize: 
    /auth
users: 
    /users
register: 
    /register
faq: 
    /faq
cart:
    /students/cart
timeline:
    /timeline
my_fields:
    /directors/my_fields
create_field:
    /directors/create_field/
create_instance:
    /directors/create_instance/
directors_list:
    /directors/directors_list
registration_info:
    /fields/
register_on_field:
    /register_on_field
change_password:
    /change_password
...
