---
registrations: 
    /registrations
authorize: 
    /authorize
users: 
    /users
register_user: 
    /users/register
faq: 
    /faq
cart:
    /cart
timeline:
    /timeline
my_fields:
    /directors/my_fields
create_field:
    /directors/create_field/
create_instance:
    /directors/create_instance/
registration_info:
    /registration_info
register_on_field:
    /register_on_field
...
