---
#name surname sex citizenship pesel_number phone_number email password
registration:
    # TODO ograniczenie znaków specjalnych w imieniu i nazwisku
    - name: name
      text: Imię
      type: text
      additional:
          - required
          - title="Imię musi składać się z przynajmniej 3 znaków."
    
    - name: surname
      text: Nazwisko
      type: text
      additional:
          - required
          - title="Nazwisko musi składać się z przynajmniej 3 znaków."
    
    - name: sex
      text: Pleć
      type: radio
      choices:
          - sex: male
            text: Mężczyzna
            additional:
                - checked
                - value="m"
          - sex: female
            text: Kobieta
            additional:
                - value="f"
    
    
    - name: citizenship
      text: Obywatelstwo
      type: text
      additional:
          - required

    # TODO pesel nie zawsze jest wymagany
    - name: number
      text: PESEL
      type: text
      additional:
          - required
          - pattern="\d{11}"
          - title="Numer pesel musi składać się z 11 cyfr."
    
    - name: phone_number
      text: Numer telefonu
      type: text
      additional:
          - required
          - pattern="(\+\d\d)?\d{9}"
          - title="Numer telefonu musi składać się z 9 cyfr ewentualnie poprzedzonym numerem kierunkowym w formacie: +44."
    
    # TODO zawarcie kropki w adresie email
    - name: email
      text: Email
      type: email
      additional:
          - required
    
    - name: password
      text: Hasło
      type: password
      additional:
          - id="password"
          - required
          - pattern="^\S{8,}$"
          - title="Hasło musi zawierać przynajmniej 8 niebiałych znaków."
    
    - name: password_c
      text: Powtórz hasło
      type: password
      additional:
          - id="confirm_password"
          - required
          - pattern="^\S{8,}$"
          - title="Hasło musi zawierać przynajmniej 8 niebiałych znaków."

...
