---
get:/faq:
  - category: "kategoria A"
    questions:
    - question: "Pytanie 1A"
      answer: "Odpowiedź 1A"
    - question: "Pytanie 2A"
      answer: "Odpowiedź 2A"
  - category: "kategoria B"
    questions:
    - question: "Pytanie 1B"
      answer: "Odpowiedź 1B"
    - question: "Pytanie 2B"
      answer: "Odpowiedź 2B"

get:/registrations:
  - name: Testowanie
    due: 20/04/2016
    registered: 20
    limit: 30
  - name: Automatyzacja
    due: 22/04/2016
    registered: 27
    limit: 30

get:/cart:
  - name: Testowanie
    due: 30/04/2016
    rank: 20
    limit: 30
    status: Rejestracja trwa
  - name: Automatyzacja
    due: 30/04/2016
    rank: 27
    limit: 30
    status: Przyjęty
  - name: Cokolwiek
    due: 30/04/2016
    rank: 32
    limit: 30
    status: Lista rezerwowa

get:/timeline:
    - text: Otwarcie rejestracji
      date: 1 czerwca 2016
      status: inactive

    - text: Koniec rejestracji
      date: 30 czerwca 2016
      status: active

    - text: Potwierdzenie rejestracji - 1 nabór
      date: 3 lipca 2016
      status: inactive

    - text: Potwierdzenie rejestracji - 2 nabór
      date: 7 lipca 2016
      status: inactive

get:/directors/my_fields:
  - name: Testowanie
    status: Aktywna rejestracja
  - name: Automatyzacja
    status: Nieaktywny
  - name: Cokolwiek
    status: Rejestracja zakończona

get:/registration_info:
  - field: field1
    mode: mode1
    info: info1
    rules: rules1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>mode1<br>
    dates: dates1
    limit: limit1
    documents: documents32
    payments: payments12
...
